import type { Metadata } from "next";
import { Biryani } from "next/font/google";
import "./styles/index.scss";

const biryani = Biryani({
	subsets: ["latin"],
	weight: ["400", "700"],
	variable: "--font-primary",
	display: "swap",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html
			className={biryani.variable}
			lang="en"
		>
			<body>{children}</body>
		</html>
	);
}
